[package]
name = "snowflakes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
futures = "0.3"
pin-project-lite = "0.2"
snow = "0.8"
tokio = "1.15"
tokio-util = { version = "0.6", features = ["codec"] }

[dev-dependencies]
anyhow = "1.0"
clap = "3.0.0-beta.5"
tokio = { version = "1.13", features = ["full"] }
snow = { version = "0.8", features = ["ring-accelerated"], default-features = false }
rand = "0.8.4"
